import Aos from "aos";
import Head from "next/head";
import { useEffect } from "react";
import Achievement from "../components/Achievement";
import Application from "../components/Application";
import Banner from "../components/Banner";
import Community from "../components/Community";
import Footer from "../components/Footer";
import Netboks from "../components/Netboks";
import News from "../components/News";
import Teams from "../components/Teams";

export default function Home() {
  useEffect(() => {
    Aos.init();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Netboks />
      <Achievement />
      <Community />
      <Teams />
      <Application />
      <News />
      <Footer />
    </div>
  );
}
